### ISSUE TITLE
사용 시 오류가 발생합니다

### ISSUE THREAD

**Issue by MagmaChipmunk** [azyu/FavoImgs#6]
19/07/31 19:40
"기본 연결이 닫혔습니다. 보내기에서 예기치 않은 오류가 발생했습니다."
메시지가 뜨며 정상적으로 작동되지 않습니다.

새로운 폴더에서 재설치 후 작동시도해보았으나 같은 오류가 발생됩니다.

**Comment by azyu** [comment]
tls 1.2 대응 문제로 파악되어 수정하였습니다.
