### ISSUE TITLE
on a REST api, cannot parse the json 가 발생하며 작동이 되지 않습니다

### ISSUE THREAD

**Issue by CODE-LA-LI-LU-LE-LO** [azyu/FavoImgs#8]
발생시간 : 21-04-15 20:00부터 현재까지
버전 : 0.6.5.0
환경 : Windows 10 Pro (버전 20H2)

![image](https://user-images.githubusercontent.com/8914838/115015562-d3ef1c00-9eee-11eb-9891-091991989984.png)

**Comment by azyu** [comment]
해당 이슈를 수정한 빌드(0.6.6.0)를 등록했습니다.
